### ISSUE TITLE
Praise for `brr-lwd`

### ISSUE THREAD

**Issue by patricoferris** [let-def/lwd#33]
Hi @let-def :))

Thanks for lwd! I've been using the [brr-lwd backend](https://github.com/let-def/lwd/tree/brr-lwd) on a few projects and have *really enjoyed* using it. I was wondering if it might be released soon? Anything I can do to help with that?

I used it in [this toplevel for Irmin](https://github.com/patricoferris/try-irmin) and also this little [application for looking at Northern Irish forest data](https://github.com/patricoferris/ni-forests).

**Comment by let-def** [comment]
Thanks for using it :). I finally found some time to merge some patches and push out a new release... https://github.com/ocaml/opam-repository/pull/20769 .

It should be available in opam at some point during the week :)

**Comment by patricoferris** [comment]
Brilliant! Thank you, I've been using it just this weekend :))

**Comment by let-def** [comment]
Released :)
