### ISSUE TITLE
Avoid unecessary computations when document is constant

### ISSUE THREAD

**Issue by Julow** [let-def/lwd#38]
It's common to have a `Lwd.map` node that performs side effects and always return the same value. This constant document must be integrated in bigger documents to receive updates but might cause unecessary computations.

```ocaml
let constant_document =
  let$ some_document in
  do_side_effect some_document;
  ()

let main =
  let$ () = constant_document in
  costly_operation
```

In this example, `do_side_effect` might interact with the DOM and `costly_operation` might wrap many of such constant documents into a sequence used as the children elements in the DOM, which will be fully evaluated every time.

Could these unnecessary computations be avoided by adding a "short circuit" node in the document ?
For example:

```ocaml
let constant_document =
  Lwd.reuse_map some_document ~cmp:(=) ~f:do_side_effect
```

**Comment by let-def** [comment]
Unfortunately I have no idea how to achieve what you are asking for, at least not without significant drawbacks.

If a computation is expensive, you should memoize it by yourself (e.g. by caching the last pair of (input, output)).
The notion of a value being the same assume we have a generic notion of equality, which is not always the case and might not even be useful: if your computation produces complex values, testing for value equality might be as expensive as recomputing. Or not, it is not for Lwd to guess :).

Furthermore, invalidation is not something that we can do partially with the current design of Lwd. If it is central to your workflow, you might want to look at [Incremental](https://github.com/janestreet/incremental), which is designed to handle this case nicely. Once you have this however, the semantics of the monadic `bind` becomes very tricky.

**Comment by Julow** [comment]
Thanks for your answer. It'd make sense to memoize `costly_operation` on its own but in my case it's code that I don't control (`Lwd_table.reduce Lwd_seq.monoid tbl`). 

Perhaps tables could handle memoization if provided with a equality function ?

**Comment by let-def** [comment]
`Lwd_table.reduce` is already highly incremental. Updates to the table are computed in O(k log n), where k is the number of changes and n is the size of the table, k << n.
If you can provide an reproducible example with performance problems, I can take a look.
