### ISSUE TITLE
Error running example code samples

### ISSUE THREAD

**Issue by CadeMichael** [let-def/lwd#45]
Trying to run either the button or tree example gives a type error when trying to build. I'm not sure if it's something with dune or the package (possible version conflicts with dune?) but the hello world example ran, but none of the UI components seemed to work and caused type errors.

button sample code error ->
```
dune build
File "tui.ml", line 10, characters 13-20:
10 | Ui_loop.run (Lwd.map button (Lwd.get vcount));;
                  ^^^^^^^
Error (warning 6 [labels-omitted]): label f was omitted in the
 application of this function.
File "tui.ml", line 10, characters 21-27:
10 | Ui_loop.run (Lwd.map button (Lwd.get vcount));;
                          ^^^^^^
Error: This expression has type int -> ui
       but an expression was expected of type 'a Lwd.t
```

code
```
open Nottui;;
module W = Nottui_widgets;;

let vcount = Lwd.var 0;;

let button count = 
  W.button (Printf.sprintf "Clicked %d times!" count)
           (fun () -> Lwd.set vcount (count + 1));;

Ui_loop.run (Lwd.map button (Lwd.get vcount));;
```

dune
```
(executable
  (name tui)
  (libraries base nottui))
```
dune-project
```
(lang dune 2.9)
(name tui)
```

**Comment by let-def** [comment]
Hi,

Dune requires labels to be explicitly specified by default. So in your example, the call to `map` should be written `Lwd.map ~f:button (Lwd.get vcount)`.
I should update https://tarides.com/blog/2020-09-24-building-portable-user-interfaces-with-nottui-and-lwd to mention that :P.

It's also possible to disable labelled argument warning by passing different flags. If I am not mistaken, that should do it:
```
(executable
  (name tui)
  (flags "-w-6")
  (libraries base nottui))
```

**Comment by CadeMichael** [comment]
Thank you!
